name: photo_data_picker
description: A new Flutter project.
version: 1.3.1+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  camera: ^0.11.0+2
  image: ^4.5.2
  path_provider: ^2.1.5
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
