name: photo_data_picker
description: A new Flutter project.
version: 1.1.2+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  camera: ^0.10.0+1
  google_ml_vision: ^0.0.7
  image: ^4.1.3
  path_provider: ^2.0.11
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
